// HAL subject codes. Selection criteria describe a reading task, not a review of every deposit.
export const disciplines = [
  ['medecine','Médecine','1.sdv.mhep','Lire le protocole avant la conclusion','Repère le type d’étude, la population, le critère principal et la durée du suivi. Distingue les résultats mesurés de leur interprétation. Un travail déposé ne suffit pas à établir une conduite clinique.','these-medecine'],
  ['sante-publique','Santé publique','1.sdv.spee','Comprendre qui est représenté','Identifie le territoire, le recrutement et la période de recueil. Vérifie les dénominateurs et les données manquantes avant de comparer des pourcentages. Une association observée ne démontre pas à elle seule une causalité.','guides/questionnaire-recherche-sante'],
  ['psychologie','Psychologie','1.shs.psy','Identifier les mesures utilisées','Note le construit étudié, les instruments et leurs conditions de passation. Cherche les limites de l’échantillon et la distinction entre analyse prévue et exploration. Les conclusions dépendent de ce dispositif.','guides/lire-article-scientifique'],
  ['education','Sciences de l’éducation','1.shs.edu','Relier la pratique au contexte','Distingue description de séance, enquête sur les pratiques et évaluation d’un dispositif. Note le niveau scolaire, le terrain et le rôle du chercheur. Une expérience locale peut éclairer une question sans être généralisable.','guides/etude-de-cas'],
  ['gestion','Gestion et management','1.shs.gestion','Passer du cas au raisonnement','Identifie l’organisation, le problème de gestion et les indicateurs disponibles. Sépare discours des acteurs, documents internes et observations. Discute ce que le cas permet d’expliquer et ce qui reste propre à cette organisation.','guides/etude-de-cas'],
  ['economie','Économie','1.shs.eco','Retrouver les hypothèses du modèle','Note la source des données, la période, l’unité d’observation et la construction des variables. Les coefficients se lisent avec leurs unités et les hypothèses du modèle ; leur taille seule ne suffit pas.','guides/donnees-quantitatives'],
  ['droit','Droit','1.shs.droit','Vérifier la portée des références','Relève la juridiction, la date et la version des textes discutés. Sépare une règle applicable, une décision et le commentaire de l’auteur. Vérifie les évolutions depuis la publication auprès des sources juridiques officielles.','guides/fiche-lecture'],
  ['sociologie','Sociologie','1.shs.socio','Situer le terrain et les catégories','Observe comment l’auteur construit ses catégories et accède au terrain. Dans un entretien, conserve le contexte du propos. Compare les cas qui soutiennent l’analyse et ceux qui la nuancent.','guides/analyse-entretiens'],
  ['histoire','Histoire','1.shs.hist','Retracer la provenance des sources','Distingue archives, éditions de documents et travaux d’historiens. Identifie la période, l’espace et les lacunes du corpus. Conserve les cotes et les pages exactes des documents que tu consultes.','guides/fiche-lecture'],
  ['linguistique','Langues et linguistique','1.shs.langue','Décrire le corpus avant de comparer','Note la langue, le genre des textes, la taille du corpus et les choix d’annotation. Une fréquence dépend du découpage et du contexte. Garde un exemple précis pour chaque phénomène discuté.','guides/corpus-recherche'],
  ['litterature','Littérature','1.shs.litt','Relier la lecture à un passage','Identifie l’édition, les pages et la question critique. Distingue l’analyse textuelle de la réception de l’œuvre. Appuie ton commentaire sur des passages situés, sans réduire une œuvre à un résumé.','guides/corpus-recherche'],
  ['communication','Information et communication','1.shs.info','Documenter le dispositif étudié','Note le support, les acteurs, la période et le mode de constitution du corpus. La visibilité d’un contenu ne mesure pas automatiquement son effet. Compare les discours aux conditions de circulation.','guides/corpus-recherche'],
  ['informatique','Informatique','0.info','Examiner la comparaison expérimentale','Repère le problème, les jeux de données, les méthodes de référence et les métriques. Cherche les conditions de reproduction et les limites. Un résultat sur un jeu de test ne garantit pas une performance dans ton contexte.','guides/reproductibilite'],
  ['ingenierie','Sciences de l’ingénieur','0.spi','Relier le résultat aux contraintes','Lis le cahier des charges, les conditions d’essai et les unités. Distingue simulation, prototype et mesure. Vérifie les tolérances, les hypothèses physiques et les limites du dispositif avant de réutiliser un résultat.','guides/reproductibilite'],
  ['mathematiques','Mathématiques','0.math','Suivre les hypothèses de la preuve','Identifie les définitions, les hypothèses du résultat et les lemmes utilisés. Un théorème ne s’applique qu’à ses conditions. Reprends un exemple simple et cherche ce qui échoue si une hypothèse est retirée.','guides/fiche-lecture'],
  ['physique','Physique','0.phys','Vérifier échelles, unités et incertitudes','Note le régime étudié, les approximations et les conditions aux limites. Distingue modèle et mesure. Les barres d’erreur et l’étalonnage font partie du résultat, tout autant que la valeur centrale.','guides/donnees-quantitatives'],
  ['chimie','Chimie','0.chim','Lire les conditions expérimentales','Relève les réactifs, conditions, méthodes de caractérisation et incertitudes décrites. Compare des résultats obtenus dans des conditions compatibles. Une notice bibliographique ne remplace ni le protocole complet ni les règles du laboratoire.','guides/reproductibilite'],
  ['environnement','Environnement','0.sde','Préciser les limites du système','Note l’échelle spatiale, la période, les scénarios et les frontières du système étudié. Compare les indicateurs à périmètre constant. Distingue une mesure, une projection et une hypothèse de scénario.','guides/donnees-quantitatives'],
  ['geographie','Géographie','1.shs.geo','Lire une carte avec sa méthode','Identifie la source, la date, l’échelle et le découpage spatial des données. Des agrégations différentes peuvent modifier l’interprétation. Note les zones absentes et ce que la représentation masque.','guides/etude-de-cas'],
  ['philosophie','Philosophie','1.shs.phil','Reconstruire l’argument','Distingue la thèse défendue, les prémisses, les objections et les réponses. Définis les termes dans leur contexte plutôt que par une définition isolée. Cite l’édition et le passage sur lesquels porte ton analyse.','guides/revue-litterature']
].map(([id,label,halCode,readingTitle,reading,guide])=>({id,label,halCode,readingTitle,reading,guide}));

export const documentTypes={THESE:'Thèse',MEM:'Mémoire',ART:'Article',REPORT:'Rapport de recherche',HDR:'Habilitation'};
