export const services=[
 {id:'plan',slug:'plan-memoire',title:'Construire le plan de mon mémoire',description:'Passe de ta question et de tes consignes à une structure que tu peux discuter avec ton encadrant.',input:'Ton sujet, ta problématique, le niveau, la filière et les consignes de rédaction.',output:'Une proposition de plan hiérarchisé, des objectifs et des points de cohérence à vérifier.',guide:'guides/question-recherche',boundary:'Le plan reste une proposition. Fais valider le périmètre et la méthode avant le recueil.'},
 {id:'references',slug:'bibliographie',title:'Organiser ma bibliographie',description:'Rassemble les références sélectionnées et prépare une présentation cohérente avec le style demandé.',input:'Les sources réelles sélectionnées dans ton projet et le style bibliographique demandé.',output:'Une bibliographie à vérifier, avec les informations manquantes signalées.',guide:'guides/zotero-bibliographie',boundary:'Les métadonnées ne prouvent pas le contenu d’un article. Vérifie la version et les champs avant de citer.'},
 {id:'redaction',slug:'travailler-une-section',title:'Travailler une section du mémoire',description:'Développe un raisonnement à partir de ton plan validé, de tes arguments et de passages réellement consultés.',input:'Un plan validé, le chapitre concerné, tes arguments et au moins une source avec un extrait lu.',output:'Un brouillon de section modifiable, des appuis bibliographiques et les lacunes à compléter.',guide:'guides/discussion-memoire',boundary:'Tu relis, corriges et assumes le texte. Les informations sans appui doivent être vérifiées ; aucun résultat ne doit être inventé.'},
 {id:'questionnaire',slug:'questionnaire',title:'Préparer mon questionnaire',description:'Relie les questions, les variables et les objectifs avant de lancer ton recueil.',input:'La population, les variables, les objectifs et les conditions de recueil.',output:'Des propositions de questions, un dictionnaire de variables et une matrice objectifs-items.',guide:'guides/questionnaire-recherche-sante',boundary:'Un questionnaire proposé n’est pas un instrument validé. Prévois une relecture et un essai dans les conditions autorisées.'},
 {id:'interview',slug:'entretien',title:'Préparer mes entretiens',description:'Construis des thèmes, des questions ouvertes et des relances adaptées à ta recherche.',input:'Les personnes à interroger, les objectifs, la durée et les consignes de ton protocole.',output:'Une trame d’entretien à tester, avec ouverture, thèmes, relances et clôture.',guide:'guides/guide-entretien',boundary:'Vérifie le consentement, les conditions d’enregistrement et les règles de ton établissement avant le recueil.'},
 {id:'dataanalysis',slug:'analyse-donnees',title:'Comprendre mes résultats',description:'Prépare une lecture structurée des données et sorties statistiques que tu fournis.',input:'Des données ou sorties réelles, leurs unités, la méthode et le logiciel utilisé.',output:'Une aide à l’interprétation et des vérifications ou commandes à examiner dans ton logiciel.',guide:'guides/donnees-quantitatives',boundary:'Ce module n’exécute pas SPSS et ne certifie pas les calculs. Il ne remplace pas la validation d’une analyse statistique.'},
 {id:'correction',slug:'relecture',title:'Relire et clarifier mon texte',description:'Travaille la précision, l’enchaînement des idées et la langue en conservant tes chiffres et références.',input:'Ton texte et les remarques de ton encadrant.',output:'Une proposition de correction et un relevé des changements à revoir.',guide:'guides/citations-plagiat',boundary:'La relecture ne mesure ni plagiat ni probabilité de rédaction automatique. Les citations se vérifient dans les sources.'},
 {id:'ppt',slug:'presentation',title:'Préparer ma présentation',description:'Choisis le fil conducteur et transforme tes résultats en un support de soutenance modifiable.',input:'La synthèse du mémoire, les résultats établis, la durée et les éléments à valoriser.',output:'Une proposition de diapositives avec notes orales, exportable en PowerPoint.',guide:'guides/presentation-soutenance-pfe',boundary:'Relis les chiffres, répète à voix haute et adapte le support au temps réellement accordé.'},
 {id:'defense',slug:'soutenance',title:'M’entraîner pour la soutenance',description:'Prépare un discours clair et des pistes de réponse aux questions sur ton travail.',input:'Ta question, la méthode, les résultats, les limites et les points difficiles.',output:'Une trame orale, des questions d’entraînement et des pistes de réponse.',guide:'guides/repondre-jury',boundary:'Les questions sont des exercices. Elles ne prédisent pas celles de ton jury.'}
];
export const researchProviders=[
 {id:'scholar',name:'Google Scholar',short:'GS',url:'https://scholar.google.com/',label:'Explorer plusieurs disciplines',description:'Repérer des publications, suivre des citations et rechercher des versions accessibles.',guide:'guides/recherche-google-scholar'},
 {id:'hal',name:'HAL',short:'HAL',url:'https://hal.science/',label:'Archives ouvertes',description:'Retrouver les dépôts d’articles, de thèses et d’autres travaux, avec leurs versions et leurs droits.',guide:'guides/recherche-hal'},
 {id:'pubmed',name:'PubMed',short:'PM',url:'https://pubmed.ncbi.nlm.nih.gov/',label:'Médecine et sciences de la santé',description:'Construire une recherche biomédicale et examiner les informations d’indexation.',guide:'guides/recherche-pubmed'},
 {id:'theses',name:'theses.fr',short:'TH',url:'https://theses.fr/',label:'Thèses en France',description:'Rechercher une thèse et consulter les informations disponibles sur sa préparation ou sa soutenance.',guide:'guides/these-doctorat'},
 {id:'zotero',name:'Zotero',short:'Z',url:'https://www.zotero.org/',label:'Gérer les références',description:'Organiser les documents et préparer les citations avec un gestionnaire de bibliographie.',guide:'guides/zotero-bibliographie'},
 {id:'prisma',name:'PRISMA',short:'PR',url:'https://www.prisma-statement.org/',label:'Rendre compte d’une revue',description:'Consulter les repères de présentation d’une revue systématique et les schémas de sélection.',guide:'guides/revue-systematique'}
];
