import { pages, templateResources, resourceTopic } from '../content/catalog.mjs';
import { escapeHtml as e, layout, metadata } from './seo.mjs';

const topics = [['all','Tous les thèmes'],['pfe','PFE et problématique'],['stage','Rapport de stage'],['oral','Soutenance'],['health','ISPITS et médecine'],['method','Méthode, sources et données']];
const searchText = page => [page.title,page.category,page.lead,...(page.keywords || []),page.body].join(' ');
const resourceCard = page => `<article class="library-card" data-resource data-topic="${resourceTopic(page)}" data-search="${e(searchText(page))}"><span class="resource-type">${page.kind === 'guide' ? 'Guide pratique' : 'Dossier de méthode'}</span><h3><a href="/${page.slug}">${e(page.heading)}</a></h3><p>${e(page.lead)}</p><a class="resource-link" href="/${page.slug}">Lire et appliquer <span aria-hidden="true">↗</span></a></article>`;
const templateCard = item => `<article class="library-card template-card" data-resource data-topic="${item.topic}" data-search="${e(item.title+' '+item.description+' '+item.keywords)}"><span class="resource-type">Modèle Word · Gratuit</span><h3>${e(item.title)}</h3><p>${e(item.description)}</p><a class="resource-link" href="${item.path}" download>Télécharger le modèle .docx <span aria-hidden="true">↓</span></a><a class="template-guide" href="${item.guide}">Lire le guide associé</a></article>`;

export function renderLibrary(context) {
  const title = 'Bibliothèque PFE, rapport de stage et soutenance';
  const description = 'Guides gratuits, exemples commentés et modèles Word pour préparer ton PFE, rapport de stage ou soutenance. Recherche par sujet et étape de travail.';
  const content = `<main id="contenu"><section class="library-hero"><div class="library-intro"><span class="eyebrow">La bibliothèque Soutenance Pro</span><h1>Une bonne méthode.<br>Un exemple pour avancer.</h1><p>Un plan à construire, une introduction qui bloque, un oral à préparer ? Trouve une explication, un exemple commenté et une prochaine étape concrète.</p><div class="library-facts"><span>${pages.length} guides et dossiers</span><span>${templateResources.length} modèles Word modifiables</span><span>Lecture sans inscription</span></div></div><aside class="library-note"><span class="resource-type">Maroc · Algérie · Francophonie</span><h2>Ton établissement garde le dernier mot.</h2><p>Les méthodes proposées s’adaptent à ton contexte. Vérifie le guide de ton école ou de ta faculté : aucun modèle ne remplace ses consignes.</p><a href="/methode-editoriale">Comment nos ressources sont préparées</a></aside></section>
<section class="library-content" aria-label="Ressources"><form class="library-search" data-library-form hidden role="search"><div><label for="library-query">Quel sujet cherches-tu ?</label><input id="library-query" name="q" type="search" maxlength="240" placeholder="Ex. introduction, plan de stage, bibliographie…" autocomplete="off"></div><div><label for="library-topic">Thème</label><select id="library-topic" name="topic">${topics.map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></div><button type="reset" hidden>Tout afficher</button><button class="site-button" type="submit">Rechercher</button></form><noscript><p>Toutes les ressources sont disponibles ci-dessous. Tu peux les consulter sans activer JavaScript.</p></noscript><p class="library-result-count" id="library-count" role="status" aria-live="polite">${pages.length+templateResources.length} ressources disponibles</p><div id="library-empty" class="library-empty" hidden><h2>Aucune ressource pour cette recherche.</h2><p>Essaie un terme plus court : « stage », « plan », « sources » ou « soutenance », ou choisis tous les thèmes.</p></div>
<section data-resource-group><div class="library-section-title"><span class="eyebrow">Comprendre et appliquer</span><h2>Les guides de travail</h2></div><div class="library-grid">${pages.map(resourceCard).join('')}</div></section>
<section data-resource-group><div class="library-section-title"><span class="eyebrow">À compléter avec ton propre travail</span><h2>Les modèles à télécharger</h2><p>Des documents Word originaux, avec des champs guidés. Remplace les indications entre crochets par tes informations et tes observations réelles.</p></div><div class="library-grid">${templateResources.map(templateCard).join('')}</div></section></section>
<section class="bottom-cta"><div><span class="eyebrow">De la ressource au projet</span><h2>Garde tes consignes et tes sources ensemble.</h2><p>L’espace gratuit te permet de préparer ton propre projet, de réviser tes textes et d’exporter tes documents.</p></div><a class="site-button" href="/#inscription">Essayer l’espace gratuit</a></section></main><script type="module" src="/assets/library.js"></script>`;
  return layout({title,description,meta:metadata({...context,path:'/bibliotheque',title,description,breadcrumbs:[{name:'Accueil',path:'/'},{name:'Bibliothèque',path:'/bibliotheque'}],collection:pages.map(page=>({name:page.title,path:'/'+page.slug}))}),content,intent:'general'});
}

export function renderEditorialMethod(context) {
  const title = 'À propos de la bibliothèque et de notre méthode';
  const description = 'Origine des ressources Soutenance Pro, rôle des exemples, vérification des références, corrections et limites de notre aide académique.';
  const content = `<main id="contenu"><section class="article-hero"><div class="article-hero-inner"><span class="eyebrow">Soutenance Pro · Publication indépendante</span><h1>Comprendre d’où vient une ressource.</h1><p class="article-lead">Un guide doit t’aider à prendre une décision et à produire ton propre travail. Voici le cadre de notre bibliothèque.</p></div></section><article class="method-page article-body"><h2>Ce que tu trouveras ici</h2><p>La bibliothèque réunit des explications, des exemples pédagogiques et des modèles originaux pour le PFE, le rapport de stage et la soutenance. Les parcours ISPITS et médecine complètent ces ressources générales. Le public visé comprend les étudiants francophones du Maroc et d’Algérie, avec des consignes qui varient selon les établissements.</p><h2>Exemples et modèles</h2><p>Les situations inventées sont indiquées comme fictives. Elles montrent comment structurer une réponse ; elles ne constituent pas des expériences de stage, des enquêtes ou des résultats à présenter comme les tiens. Les modèles Word contiennent des champs à compléter avec tes informations réelles.</p><h2>Sources et rédaction</h2><p>Les liens universitaires ou documentaires permettent de retrouver les recommandations évoquées. Les explications sont adaptées et reformulées ; les documents d’autres étudiants ne sont pas redistribués dans cette bibliothèque. La préparation des ressources peut utiliser une assistance IA. Cela ne constitue ni une validation par ton établissement ni une garantie d’absence d’erreur.</p><p>Quand une date de mise à jour est affichée, elle correspond à une modification du contenu. Une date récente ne remplace pas la lecture des sources. Vérifie aussi que le document de référence concerne bien ton diplôme et ton année.</p><h2>Ton travail, tes décisions</h2><p>Tu restes responsable de tes observations, de tes données, des références et de la version déposée. Utilise les outils pour organiser, comprendre et réviser. Ne présente pas un exemple ou un texte généré comme une recherche que tu aurais réalisée. Les règles de ton établissement sur l’usage de l’IA s’appliquent à ton projet.</p><h2>Indépendance</h2><p>Soutenance Pro est un service indépendant. La mention d’un ISPITS, d’une université ou d’une faculté ne signifie pas une affiliation ou une approbation. Nous ne promettons ni note, ni admission, ni validation automatique d’un travail.</p><h2>Signaler une correction</h2><p>Tu peux signaler une erreur via <a href="https://wa.me/212708186441" target="_blank" rel="noopener noreferrer">WhatsApp Soutenance Pro</a> ou <a href="https://www.instagram.com/soutenancepro.co/" target="_blank" rel="noopener noreferrer">Instagram</a>. Indique l’adresse du guide, le passage concerné et, si possible, une source permettant de vérifier la correction. N’envoie pas de données personnelles de participants ou de patients.</p><p><a href="/bibliotheque">Retourner à la bibliothèque</a></p></article></main>`;
  return layout({title,description,meta:metadata({...context,path:'/methode-editoriale',title,description}),content,intent:'general'});
}
