import { referenceText,referenceRIS,referenceBib } from '../shared/reference-format.js';
export function researchUrl(provider,q){const query=String(q||'').trim().slice(0,240);if(!query)return null;const paths={scholar:['https://scholar.google.com/scholar','q'],hal:['https://hal.science/search/index','q'],pubmed:['https://pubmed.ncbi.nlm.nih.gov/','term'],theses:['https://theses.fr/','q']};if(!Object.hasOwn(paths,provider))return null;const [base,param]=paths[provider],url=new URL(base);url.searchParams.set(param,query);return url.href;}
const milestones=[['Question et périmètre',.1],['Lectures et protocole',.25],['Matériaux ou recueil',.5],['Analyse et résultats',.68],['Rédaction et discussion',.82],['Retours et corrections',.93],['Vérification et dépôt',1]];
export function makeSchedule(start,end){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))throw new Error('Vérifie les deux dates.');const a=Date.parse(start+'T12:00:00Z'),b=Date.parse(end+'T12:00:00Z'),days=Math.round((b-a)/86400000);if(!Number.isFinite(days)||days<7||days>1096||new Date(a).toISOString().slice(0,10)!==start||new Date(b).toISOString().slice(0,10)!==end)throw new Error('Choisis une période valide entre 7 jours et 3 ans.');return milestones.map(([name,fraction])=>({name,date:new Date(a+Math.round(days*fraction)*86400000).toISOString().slice(0,10)}));}
export function textStats(text){const value=String(text||'');const words=value.match(/[\p{L}\p{N}]+(?:[’'’-][\p{L}\p{N}]+)*/gu)||[];return {words:words.length,characters:[...value].length,paragraphs:value.trim()?value.trim().split(/\n\s*\n/).length:0};}
export function manualReference(values){const title=String(values.title||'').trim(),authors=String(values.authors||'').split(/\n/).map(x=>x.trim()).filter(Boolean);if(!title||!authors.length)throw new Error('Ajoute le titre et les auteurs.');let url;try{url=new URL(values.url);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error();}catch{throw new Error('Ajoute un lien HTTP ou HTTPS valide vers le document.');}const doi=String(values.doi||'').trim().replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'');if(doi&&!/^10\.\d{4,9}\/\S+$/.test(doi))throw new Error('Vérifie le DOI ou laisse ce champ vide.');const year=values.year?Number(values.year):null;if(year!==null&&(!Number.isInteger(year)||year<1000||year>2100))throw new Error('Vérifie l’année.');return {id:'ma-reference',title:title.slice(0,1200),authors:authors.slice(0,100),year,url:url.href,doi,type:['ART','THESE','MEM','REPORT'].includes(values.type)?values.type:'OTHER',journal:String(values.journal||'').slice(0,500)};}
function download(contents,name,type){const url=URL.createObjectURL(new Blob([contents],{type})),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setup(){for(const form of document.querySelectorAll('[data-tool]')){const type=form.dataset.tool;form.hidden=false;
 if(type==='search'){form.addEventListener('submit',event=>{event.preventDefault();const url=researchUrl(form.elements.provider.value,form.elements.q.value);if(url)location.assign(url);});}
 if(type==='references'){let current=null;form.addEventListener('submit',event=>{event.preventDefault();try{current=manualReference(Object.fromEntries(new FormData(form)));form.elements.reference.value=referenceText(current);form.querySelector('[data-output]').hidden=false;form.querySelector('[data-status]').textContent='Référence préparée. Vérifie les champs avant de l’utiliser.';}catch(error){current=null;form.querySelector('[data-output]').hidden=true;form.querySelector('[data-status]').textContent=error.message;}});form.addEventListener('input',event=>{if(event.target.name!=='reference'){current=null;form.querySelector('[data-output]').hidden=true;}});form.querySelectorAll('[data-export]').forEach(button=>button.addEventListener('click',()=>{if(current)download(button.dataset.export==='ris'?referenceRIS(current):referenceBib(current),'soutenance-pro-reference.'+button.dataset.export,'text/plain;charset=utf-8');}));}
 if(type==='planning'){let schedule=null;form.addEventListener('submit',event=>{event.preventDefault();try{schedule=makeSchedule(form.elements.start.value,form.elements.end.value);const tbody=form.querySelector('tbody');tbody.replaceChildren(...schedule.map(item=>{const row=document.createElement('tr');for(const value of [item.name,new Date(item.date+'T12:00:00Z').toLocaleDateString('fr-FR',{timeZone:'UTC'})]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}return row;}));form.querySelector('[data-output]').hidden=false;form.querySelector('[data-status]').textContent='Trame créée. Ajuste-la aux dépendances réelles de ton projet.';}catch(error){schedule=null;form.querySelector('[data-output]').hidden=true;form.querySelector('[data-status]').textContent=error.message;}});form.addEventListener('input',()=>{schedule=null;form.querySelector('[data-output]').hidden=true;});form.querySelector('[data-export]').addEventListener('click',()=>{if(schedule)download('\uFEFFJalon;Date\n'+schedule.map(x=>`"${x.name}";${x.date}`).join('\n'),'soutenance-pro-calendrier.csv','text/csv;charset=utf-8');});}
 if(type==='text'){const update=()=>{const stats=textStats(form.elements.text.value);form.querySelector('output').textContent=`${stats.words.toLocaleString('fr-FR')} mots · ${stats.characters.toLocaleString('fr-FR')} caractères · ${stats.paragraphs} paragraphes`;};form.addEventListener('input',update);update();}
 if(type==='citations'){const update=()=>{form.querySelector('output').textContent=`${form.querySelectorAll('input:checked').length} points vérifiés sur 6 · suivi de relecture, sans score de similitudes`;};form.addEventListener('change',update);form.addEventListener('reset',()=>setTimeout(update,0));}
}}
if(typeof document!=='undefined')setup();
